# Generated by Django 2.2.6 on 2019-10-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('correo', models.EmailField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('mensaje', models.TextField(max_length=500)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
